version: '3.4'

services:
  nginx:
    image: nginx
    ports:
      - 81:80
      - 443:443
    depends_on:
      - web
    volumes:
      - ./staticfiles:/home/app/web/staticfiles
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
      # - ./certbot/www:/var/www/certbot/:ro
      # - ./certbot/conf/:/etc/nginx/ssl/:ro
  # certbot:
  #   image: certbot/certbot:latest
  #   volumes:
  #     - ./certbot/www/:/var/www/certbot/:rw
  #     - ./certbot/conf/:/etc/letsencrypt/:rw
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 ExpenseTracker.wsgi:application 
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - ./staticfiles:/tmp/ExpenseTracker/staticfiles
  postgres:    
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: expenses3_db
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgresql:/var/lib/postgresql/data