# Generated by Django 4.1.5 on 2023-02-07 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('description', models.CharField(max_length=255)),
                ('currency', models.CharField(max_length=5)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('to_currency', models.CharField(blank=True, max_length=5, null=True)),
                ('to_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('native_currency', models.CharField(max_length=5)),
                ('native_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('native_amount_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.profile')),
            ],
        ),
        migrations.CreateModel(
            name='AppTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('description', models.CharField(max_length=255)),
                ('currency', models.CharField(max_length=5)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('to_currency', models.CharField(blank=True, max_length=5, null=True)),
                ('to_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('native_currency', models.CharField(max_length=5)),
                ('native_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('native_amount_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_kind', models.CharField(max_length=255)),
                ('transaction_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.profile')),
            ],
        ),
    ]
