# Generated by Django 4.1.5 on 2023-02-14 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apptransaction',
            name='amount',
            field=models.DecimalField(decimal_places=13, max_digits=20),
        ),
        migrations.AlterField(
            model_name='apptransaction',
            name='currency',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='apptransaction',
            name='native_amount',
            field=models.DecimalField(decimal_places=13, max_digits=20),
        ),
        migrations.AlterField(
            model_name='apptransaction',
            name='native_amount_usd',
            field=models.DecimalField(decimal_places=13, max_digits=20),
        ),
        migrations.AlterField(
            model_name='apptransaction',
            name='native_currency',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='apptransaction',
            name='to_amount',
            field=models.DecimalField(blank=True, decimal_places=13, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='apptransaction',
            name='to_currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=13, max_digits=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='native_amount',
            field=models.DecimalField(decimal_places=13, max_digits=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='native_amount_usd',
            field=models.DecimalField(decimal_places=13, max_digits=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='native_currency',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='to_amount',
            field=models.DecimalField(blank=True, decimal_places=13, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='to_currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
